# Change these first
owner: fblampe # Your GitHub organization or username, where this repository lives
repo: localzero-monitoring-upptime # The name of this repository

sites:
  - name: LocalZero Monitoring (prod)
    url: https://monitoring.localzero.net/
  - name: LocalZero Monitoring (test)
    url: https://monitoring-test.localzero.net/
    headers:
    - "Authorization: Basic $TESTING_BASIC_AUTH"

status-website:
  baseUrl: /localzero-monitoring-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Site status of LocalZero Monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
